### ISSUE TITLE
No kernel found in database

### ISSUE THREAD

**Issue by seliayeu** [Raphael-Hao/brainstorm#49]
I am trying to reproduce the results for the Switch MoE benchmark. When I run `python benchmark/switch_moe/benchmark.py --mode throughput --vendor brt --expert 16`, I get the following error: 

```
ValueError: No kernel found in database with identifier = '{"device_name": "NVIDIA_TITAN_X_(Pascal)", "input_infos": {"input_0": [16, 768]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [16, 3072]}, "parameters": {"in_features": 768, "out_features": 3072}}', objective_func = 'fastest'
```

**Comment by Raphael-Hao** [comment]
We only provide the GPU kernel tuned on `A100-80GB` for evaluating switch moe. If you want to run it on a `Titan-X` GPU, you have to tune the related kernels with TVM by yourself and inject it into the kernel db. You can find related scripts [here](https://github.com/Raphael-Hao/brainstorm/blob/main/benchmark/micro/kernels/linear_3078_768.py)

**Comment by seliayeu** [comment]
Thanks, that script worked.
